#!/usr/bin/env python3
"""Generate per-harness adapters from core/.

Single source of truth: core/charter.md, core/protocols/*.md, core/digests.md.
Everything this script writes carries a GENERATED marker — edit core/, then rerun:

    python tools/build.py

Placeholders in core files:
    {{GO:name}} / {{go:name}}  -> harness-appropriate "run this protocol" phrase,
                                  capitalized as a sentence / lowercase mid-sentence.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "core"
ADAPTERS = ROOT / "adapters"

PROTOCOLS = ["preflight", "deep-debug", "stuck", "landing"]

# Where protocol files live inside a *target* repo for file-referencing harnesses.
PROTOCOL_DIR = "docs/fablized"

GENERATED = "<!-- GENERATED by tools/build.py from core/ — edit core/, not this file. -->"


def parse(path: Path):
    """Split a core file into (frontmatter dict or None, body)."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---\n"):
        _, fm, body = text.split("---\n", 2)
        meta = {}
        key = None
        for line in fm.rstrip("\n").split("\n"):
            if re.match(r"^\S", line) and ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip()] = val.strip()
            elif key:  # continuation line
                meta[key] += " " + line.strip()
        return meta, body.lstrip("\n")
    return None, text


def load():
    charter = parse(CORE / "charter.md")[1]
    protocols = {}
    for name in PROTOCOLS:
        meta, body = parse(CORE / "protocols" / f"{name}.md")
        protocols[name] = {"meta": meta, "body": body}
    digests = parse(CORE / "digests.md")[1]
    return charter, protocols, digests


# --- reference styles: how each harness tells the model to run a protocol ---

def ref_claude(name, title):
    return f"invoke the `{name}` skill"

def ref_file(name, title):
    return f"open `{PROTOCOL_DIR}/{name}.md` and follow it"

def ref_cursor(name, title):
    return (f"apply the `fablized-{name}` rule "
            f"(if it did not auto-load, open `.cursor/rules/fablized-{name}.mdc`)")

def ref_inline(name, title):
    return f"follow the {title} protocol below"

def ref_digest(name, title):
    return f"apply the {title} digest below"


def substitute(text, ref, titles):
    def repl(m):
        cap, name = m.group(1) == "GO", m.group(2)
        phrase = ref(name, titles[name])
        if cap:
            phrase = phrase[0].upper() + phrase[1:] + "."
        return phrase
    return re.sub(r"\{\{(GO|go):([a-z-]+)\}\}", repl, text)


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def main():
    charter, protocols, digests = load()
    titles = {n: p["meta"]["title"] for n, p in protocols.items()}

    def charter_for(ref):
        return substitute(charter, ref, titles)

    def body_for(name, ref):
        return substitute(protocols[name]["body"], ref, titles)

    # --- Claude Code (installed at repo root: dogfooded by this repo itself) ---
    write(ROOT / "CLAUDE.md", f"{GENERATED}\n\n{charter_for(ref_claude)}")
    for name, p in protocols.items():
        fm = f"---\nname: {p['meta']['name']}\ndescription: {p['meta']['description']}\n---"
        write(ROOT / ".claude" / "skills" / name / "SKILL.md",
              f"{fm}\n{GENERATED}\n\n{body_for(name, ref_claude)}")

    # --- shared protocol files for file-referencing harnesses -----------------
    # Install alongside AGENTS.md / GEMINI.md / copilot-instructions.md by
    # copying adapters/protocol-files/docs/fablized/ into the target repo.
    for name in PROTOCOLS:
        write(ADAPTERS / "protocol-files" / "docs" / "fablized" / f"{name}.md",
              f"{GENERATED}\n\n{body_for(name, ref_file)}")

    # --- AGENTS.md standard (Codex CLI, Amp, Jules, Zed, Cursor ≥1.0, ...) ----
    preamble = (f"{GENERATED}\n"
                f"<!-- Requires the protocol files: copy adapters/protocol-files/"
                f"{PROTOCOL_DIR}/ into this repo at {PROTOCOL_DIR}/. -->\n\n")
    write(ADAPTERS / "agents-md" / "AGENTS.md", preamble + charter_for(ref_file))

    # --- Gemini CLI ------------------------------------------------------------
    write(ADAPTERS / "gemini" / "GEMINI.md", preamble + charter_for(ref_file))

    # --- GitHub Copilot ---------------------------------------------------------
    write(ADAPTERS / "copilot" / ".github" / "copilot-instructions.md",
          preamble + charter_for(ref_file))

    # --- Cursor rules ------------------------------------------------------------
    write(ADAPTERS / "cursor" / ".cursor" / "rules" / "fablized-charter.mdc",
          f"---\ndescription: Fablized charter — core working discipline\n"
          f"globs:\nalwaysApply: true\n---\n{GENERATED}\n\n{charter_for(ref_cursor)}")
    for name, p in protocols.items():
        write(ADAPTERS / "cursor" / ".cursor" / "rules" / f"fablized-{name}.mdc",
              f"---\ndescription: {p['meta']['description']}\n"
              f"globs:\nalwaysApply: false\n---\n{GENERATED}\n\n{body_for(name, ref_cursor)}")

    # --- raw system prompts (any model via API, orchestrators, other harnesses) ---
    full = [f"{GENERATED}\n", charter_for(ref_inline)]
    for name in PROTOCOLS:
        full.append(f"\n---\n\n# Protocol: {titles[name]}\n")
        # drop the duplicate H1 the body already carries
        body = re.sub(r"^# .+\n", "", body_for(name, ref_inline), count=1)
        full.append(body)
    write(ADAPTERS / "system-prompt" / "fablized-full.md", "\n".join(full))

    compact = (f"{GENERATED}\n\n{charter_for(ref_digest)}\n\n---\n\n"
               + substitute(digests, ref_digest, titles))
    write(ADAPTERS / "system-prompt" / "fablized-compact.md", compact)

    print("done.")


if __name__ == "__main__":
    sys.exit(main())
