#!/usr/bin/env python3
"""Generate per-harness adapters from core/.

Single source of truth: core/charter.md, core/guardrails.md, core/part2-template.md,
core/protocols/*.md, core/digests.md. Everything this script writes carries a GENERATED
marker — edit core/, then rerun:

    python tools/build.py

Placeholders in core files:
    {{GO:name}} / {{go:name}}  -> harness-appropriate "run this protocol" phrase,
                                  capitalized as a sentence / lowercase mid-sentence.

Budgets (build FAILS over budget, per marching orders + Amendment 01):
    AGENTS.md                                 <= 1800 words
    adapters/system-prompt/fablized-micro.md  <= 1200 words
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "core"
ADAPTERS = ROOT / "adapters"

PROTOCOLS = [
    "preflight", "deep-debug", "stuck", "landing",
    "secure-coding", "destructive-ops", "delegation", "session-continuity",
]
# The micro build inlines only these digest sections (Amendment 01: charter digest
# + four protocol digests + guardrail one-liners).
MICRO_DIGESTS = ["Charter digest", "Guardrails digest",
                 "Preflight digest", "Deep-debug digest",
                 "Stuck digest", "Landing digest"]

AGENTS_BUDGET = 1800
MICRO_BUDGET = 1200

# Where protocol files live inside a *target* repo for file-referencing harnesses.
PROTOCOL_DIR = "docs/fablized"

GENERATED = "<!-- GENERATED by tools/build.py from core/ — edit core/, not this file. -->"

# Part 2 of AGENTS.md is agent-maintained per project. The build must never
# clobber a filled Part 2: it regenerates Part 1 (charter + guardrails) and
# preserves everything from this heading to EOF verbatim, unless the existing
# Part 2 is still the unfilled skeleton (then the fresh template flows through).
PART2_HEADING = "# Part 2 — Project Specifics (agent-maintained)"


def parse(path: Path):
    """Split a core file into (frontmatter dict or None, body)."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---\n"):
        _, fm, body = text.split("---\n", 2)
        meta = {}
        key = None
        for line in fm.rstrip("\n").split("\n"):
            if re.match(r"^\S", line) and ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip()] = val.strip()
            elif key:  # continuation line
                meta[key] += " " + line.strip()
        return meta, body.lstrip("\n")
    return None, text


def load():
    charter = parse(CORE / "charter.md")[1]
    guardrails = parse(CORE / "guardrails.md")[1]
    part2 = parse(CORE / "part2-template.md")[1]
    protocols = {}
    for name in PROTOCOLS:
        meta, body = parse(CORE / "protocols" / f"{name}.md")
        protocols[name] = {"meta": meta, "body": body}
    digests = parse(CORE / "digests.md")[1]
    return charter, guardrails, part2, protocols, digests


def digest_sections(digests: str):
    """Return (intro, ordered {section title: full section text incl. '## ' header})."""
    parts = re.split(r"(?m)^## ", digests)
    intro = parts[0].rstrip("\n")
    sections = {}
    for part in parts[1:]:
        title = part.split("\n", 1)[0].strip()
        sections[title] = "## " + part.rstrip("\n")
    return intro, sections


# --- reference styles: how each harness tells the model to run a protocol ---

def ref_claude(name, title):
    return f"invoke the `{name}` skill"

def ref_file(name, title):
    return f"open `{PROTOCOL_DIR}/{name}.md` and follow it"

def ref_cursor(name, title):
    return (f"apply the `fablized-{name}` rule "
            f"(if it did not auto-load, open `.cursor/rules/fablized-{name}.mdc`)")

def ref_inline(name, title):
    return f"follow the {title} protocol below"

def ref_digest(name, title):
    return f"apply the {title} digest below"


def substitute(text, ref, titles):
    def repl(m):
        cap, name = m.group(1) == "GO", m.group(2)
        phrase = ref(name, titles[name])
        if cap:
            phrase = phrase[0].upper() + phrase[1:] + "."
        return phrase
    return re.sub(r"\{\{(GO|go):([a-z-]+)\}\}", repl, text)


def words(text: str) -> int:
    return len(text.split())


def check_budget(label: str, content: str, budget: int) -> int:
    n = words(content)
    if n > budget:
        sys.exit(f"BUILD FAILED: {label} is {n} words (budget {budget}). "
                 f"Trim core/ sources -- digests/guardrails/part2, never the charter "
                 f"(doctrine wording is frozen).")
    return n


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def existing_part2(path: Path, skeleton_part2: str):
    """Classify the Part 2 in an existing AGENTS.md.

    Returns (mode, text): 'absent' (no file), 'skeleton' (unfilled — safe to
    regenerate), 'filled' (agent-maintained content — preserve verbatim), or
    'no-boundary' (heading not found — refuse rather than guess the splice).
    """
    if not path.exists():
        return "absent", None
    text = path.read_text(encoding="utf-8")
    idx = text.find(PART2_HEADING)
    if idx < 0:
        return "no-boundary", None
    current = text[idx:]
    if current.strip() == skeleton_part2.strip():
        return "skeleton", None
    return "filled", current


def main():
    charter, guardrails, part2, protocols, digests = load()
    titles = {n: p["meta"]["title"] for n, p in protocols.items()}
    intro, dsec = digest_sections(digests)
    counts = {}

    def charter_for(ref):
        return substitute(charter, ref, titles)

    def body_for(name, ref):
        return substitute(protocols[name]["body"], ref, titles)

    def kit_for(ref):
        """Charter + guardrails + Part 2 skeleton — the full always-on layer."""
        return f"{charter_for(ref)}\n\n---\n\n{guardrails}\n\n---\n\n{part2}"

    # --- root AGENTS.md (file-referencing: Codex / OpenCode / anything) --------
    # The budget gates what the kit SHIPS (the skeleton composition), never a
    # project's filled Part 2 — so it is always computed skeleton-side.
    skeleton_agents = f"{GENERATED}\n\n{kit_for(ref_file)}"
    counts["AGENTS.md"] = check_budget("AGENTS.md", skeleton_agents, AGENTS_BUDGET)

    force_part2 = "--force-part2" in sys.argv[1:]
    mode, preserved = existing_part2(ROOT / "AGENTS.md", part2)
    if mode == "no-boundary" and not force_part2:
        sys.exit("BUILD REFUSED: the existing AGENTS.md has no recognizable "
                 f"'{PART2_HEADING}' heading, so the Part 1 / Part 2 boundary "
                 "cannot be found and a rebuild could destroy project-specific "
                 "content. Restore the heading, or rerun with --force-part2 to "
                 "overwrite the whole file with the fresh skeleton.")
    if mode == "filled" and not force_part2:
        agents = (f"{GENERATED}\n\n{charter_for(ref_file)}\n\n---\n\n{guardrails}"
                  f"\n\n---\n\n{preserved}")
        print("  AGENTS.md: filled Part 2 detected — preserved verbatim; "
              "Part 1 regenerated (--force-part2 overwrites with the skeleton)")
    else:
        agents = skeleton_agents
    write(ROOT / "AGENTS.md", agents)

    # --- Claude Code: shim + skills -------------------------------------------
    write(ROOT / "CLAUDE.md",
          f"{GENERATED}\n\n@AGENTS.md\n\n"
          f"Claude Code note: where the charter says \"open `{PROTOCOL_DIR}/<name>.md`"
          f" and follow it\", invoke the `<name>` skill instead — the skills in"
          f" `.claude/skills/` carry the same protocols and also load by description"
          f" at phase boundaries. Project facts live in AGENTS.md Part 2 only.")
    for name, p in protocols.items():
        fm = f"---\nname: {p['meta']['name']}\ndescription: {p['meta']['description']}\n---"
        write(ROOT / ".claude" / "skills" / name / "SKILL.md",
              f"{fm}\n{GENERATED}\n\n{body_for(name, ref_claude)}")

    # --- protocol files: at repo root (so root AGENTS.md refs resolve) and in
    # --- adapters/ (for copying into target repos alongside one-file adapters) -
    for name in PROTOCOLS:
        content = f"{GENERATED}\n\n{body_for(name, ref_file)}"
        write(ROOT / "docs" / "fablized" / f"{name}.md", content)
        write(ADAPTERS / "protocol-files" / "docs" / "fablized" / f"{name}.md", content)

    # --- one-file adapters (AGENTS.md standard, Gemini, Copilot) ---------------
    preamble = (f"{GENERATED}\n"
                f"<!-- Requires the protocol files: copy adapters/protocol-files/"
                f"{PROTOCOL_DIR}/ into this repo at {PROTOCOL_DIR}/. -->\n\n")
    write(ADAPTERS / "agents-md" / "AGENTS.md", preamble + kit_for(ref_file))
    write(ADAPTERS / "gemini" / "GEMINI.md", preamble + kit_for(ref_file))
    write(ADAPTERS / "copilot" / ".github" / "copilot-instructions.md",
          preamble + kit_for(ref_file))

    # --- Cursor rules -----------------------------------------------------------
    write(ADAPTERS / "cursor" / ".cursor" / "rules" / "fablized-charter.mdc",
          f"---\ndescription: Fablized charter + guardrails — core working discipline\n"
          f"globs:\nalwaysApply: true\n---\n{GENERATED}\n\n"
          f"{charter_for(ref_cursor)}\n\n---\n\n{guardrails}")
    for name, p in protocols.items():
        write(ADAPTERS / "cursor" / ".cursor" / "rules" / f"fablized-{name}.mdc",
              f"---\ndescription: {p['meta']['description']}\n"
              f"globs:\nalwaysApply: false\n---\n{GENERATED}\n\n{body_for(name, ref_cursor)}")

    # --- raw system prompts -----------------------------------------------------
    full = [f"{GENERATED}\n", charter_for(ref_inline), "\n---\n", guardrails]
    for name in PROTOCOLS:
        full.append(f"\n---\n\n# Protocol: {titles[name]}\n")
        # drop the duplicate H1 the body already carries
        body = re.sub(r"^# .+\n", "", body_for(name, ref_inline), count=1)
        full.append(body)
    full_text = "\n".join(full)
    counts["full"] = words(full_text)
    write(ADAPTERS / "system-prompt" / "fablized-full.md", full_text)

    # Compact: full charter + full guardrails + every digest EXCEPT the charter's
    # (the charter is already present in full).
    compact_digests = "\n\n".join(
        text for title, text in dsec.items() if title != "Charter digest")
    compact = (f"{GENERATED}\n\n{charter_for(ref_digest)}\n\n---\n\n{guardrails}"
               f"\n\n---\n\n{intro}\n\n{compact_digests}")
    counts["compact"] = words(compact)
    write(ADAPTERS / "system-prompt" / "fablized-compact.md", compact)

    # Micro: digests only, fully inlined — no skills, no files to open, nothing
    # for a small model to fail to trigger (Amendment 01).
    micro_note = ("Fablized micro build for small-context models. Follow literally. "
                  "The digests below ARE the full procedure — nothing else to open, "
                  "no skills to trigger.")
    micro = (f"{GENERATED}\n\n{micro_note}\n\n"
             + "\n\n".join(dsec[t] for t in MICRO_DIGESTS))
    counts["micro"] = check_budget(
        "adapters/system-prompt/fablized-micro.md", micro, MICRO_BUDGET)
    write(ADAPTERS / "system-prompt" / "fablized-micro.md", micro)

    # --- token-cost table data (README carries the human copy — keep it current) -
    per_skill = {n: words(protocols[n]["body"]) for n in PROTOCOLS}
    # ASCII-only output: Windows consoles may be cp1252 and choke on wider glyphs.
    print("\nword counts (approx tokens = words * 1.35):")
    print(f"  AGENTS.md {counts['AGENTS.md']} | full {counts['full']} | "
          f"compact {counts['compact']} | micro {counts['micro']}")
    print("  per-skill: " + ", ".join(f"{n} {c}" for n, c in per_skill.items()))
    print("done.")


if __name__ == "__main__":
    sys.exit(main())
